version: '3.1'

services:
  postgres:
    image: postgres
    container_name: batch
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: batch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password